booking/hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .settings import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotel_app.urls')),
    path('', include('users.urls')),
] +  static(STATIC_URL, document_root=STATIC_URL)  + static('hotel_photos', document_root='hotel_photos')

booking/hotel_app/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('hotels/', views.view_hotels, name='view_hotels'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
    path('hotels/<int:item_id>', views.hotel_detail, name='hotel_detail'),
    path('hotel/rooms/', views.view_rooms, name='view_rooms'),
    path('room/', views.room_detail, name='room_detail'),
    path('room/book/', views.book_room, name='book_room'),
    path('bookings/', views.view_bookings, name='view_bookings'),
    path('leave_review/', views.leave_review, name='leave_review'),
    path('user/profile/', views.user_profile, name='user_profile'),
]

booking/hotel_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Hotel(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=150)
    description = models.TextField()
    photos = models.ImageField(upload_to='hotel_photos/')
    rating = models.DecimalField(max_digits=3, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(blank=True, null=True)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Room(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    room_type = models.CharField(max_length=50)
    photos = models.ImageField(upload_to='room_photos/')
    price_per_night = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(blank=True, null=True)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.room_type} at {self.hotel.name}"

class Booking(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in_date = models.DateField()
    check_out_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(blank=True, null=True)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"Booking: {self.room} by {self.user.username}"

class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    comment = models.TextField()
    rating = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deleted_at = models.DateTimeField(blank=True, null=True)
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return f"Review by {self.user.username} for {self.hotel.name}"

booking/hotel_app/forms.py
from django import forms
from .models import Booking, Room
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("first_name", "last_name", "username", "email")

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['room', 'check_in_date', 'check_out_date']
        widgets = {
            'check_in_date': forms.DateInput(attrs={'type': 'date'}),
            'check_out_date': forms.DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super(BookingForm, self).__init__(*args, **kwargs)
        self.fields['room'].queryset = Room.objects.filter(available=True)

    def clean(self):
        cleaned_data = super().clean()
        check_in_date = cleaned_data.get('check_in_date')
        check_out_date = cleaned_data.get('check_out_date')

        if check_in_date and check_out_date:
            if check_in_date >= check_out_date:
                raise forms.ValidationError("Дата выезда должна быть после даты заезда.")

            room = cleaned_data.get('room')
            if room:
                bookings = Booking.objects.filter(room=room, deleted=False)
                for booking in bookings:
                    if check_in_date <= booking.check_out_date and check_out_date >= booking.check_in_date:
                        raise forms.ValidationError("Эта комната уже забронирована на выбранные даты.")
        return cleaned_data

booking/hotel_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Hotel, Room, Booking, Review

def view_hotels(request, ):
    hotels = Hotel.objects.all()
    print(hotels[0], 'blyad')
    print(request.get_full_path(), 'blyad')
    return render(request, 'home_page.html', {'hotels': hotels, 'test': 'test'})

def hotel_detail(request, item_id):
    print(item_id, 'blyat2')
    hotel = Hotel.objects.get(id=item_id)
    return render(request, 'hotel_detail.html', {'hotel': hotel})

def view_rooms(request, hotel_id):
    rooms = Room.objects.filter(hotel_id=hotel_id)
    return render(request, 'view_rooms.html', {'rooms': rooms})

def room_detail(request, room_id):
    room = Room.objects.get(id=room_id)
    return render(request, 'room_detail.html', {'room': room})

@login_required
def book_room(request, room_id):
    if request.method == 'POST':
        room = Room.objects.get(id=room_id)
        check_in_date = request.POST['check_in_date']
        check_out_date = request.POST['check_out_date']

    return render(request, 'book_room.html', {'room': room})

@login_required
def view_bookings(request):
    user = request.user
    bookings = Booking.objects.filter(user=user)
    return render(request, 'view_bookings.html', {'bookings': bookings})

@login_required
def leave_review(request, hotel_id):
    if request.method == 'POST':
        hotel = Hotel.objects.get(id=hotel_id)
        comment = request.POST['comment']
        rating = request.POST['rating']

    return render(request, 'leave_review.html', {'hotel': hotel})


def user_profile(request):
    return render(request, 'user_profile.html')

@login_required
def manage_hotels(request):
    hotels = Hotel.objects.all()
    return render(request, 'manage_hotels.html', {'hotels': hotels})

@login_required
def manage_hotel_detail(request, hotel_id):
    hotel = Hotel.objects.get(id=hotel_id)
    return render(request, 'manage_hotel_detail.html', {'hotel': hotel})

@login_required
def manage_rooms(request, hotel_id):
    rooms = Room.objects.filter(hotel_id=hotel_id)
    return render(request, 'manage_rooms.html', {'rooms': rooms})

@login_required
def add_room(request, hotel_id):
    if request.method == 'POST':
        return render(request, 'add_room.html')

@login_required
def manage_bookings(request):
    bookings = Booking.objects.all()
    return render(request, 'manage_bookings.html', {'bookings': bookings})

@login_required
def modify_booking(request, booking_id):
    booking = Booking.objects.get(id=booking_id)
    if request.method == 'POST':
        return render(request, 'modify_booking.html', {'booking': booking})

@login_required
def analytics(request):
    return render(request, 'analytics.html')

booking/hotel_app/templates/base_layout.html
{% load static %}
<html>
    <head>
        <title>Online Booking Hotels</title>
        <link
            rel="stylesheet"
            type="text/css"
            href="{% static '/main.css' %}"
        />

        <script src="{% static 'js/script.js' %}"></script>
    </head>
    <body>
        <header class="header_section">
            <nav class="header_navbar">
                <a class = "header_nav_link" href="/hotels">Главная</a>
                <a class = "header_nav_link" href="{% url 'register' %}">Регистрация</a>
                <a class = "header_nav_link" href="{% url 'login' %}">Войти</a>
                <a class = "header_nav_link" href="hotels">My Link</a>
            </nav>
        </header>

        {% comment %}
        <header class="site-header">
            <h1>Онлайн магазин книг</h1>
        </header>

        <nav>
            <ul class="nav justify-content-start">
                <li class="nav-item">
                    <a class="nav-link" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/products/">Товары</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="/users/balance/"
                        >Баланс: {{ balance }}</a
                    >
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/cart/">Корзина</a>
                </li>
                {% endif %} {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link" href="/staff_orders/">Заказы</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/staff_orders/add_product/"
                        >Добавить товар</a
                    >
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/staff_orders/delete_product/"
                        >Удалить товар</a
                    >
                </li>
                {% endif %}

                <ul class="nav justify-content-end">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Выход</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}"
                            >Регистрация</a
                        >
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Войти</a>
                    </li>
                    {% endif %} {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="/staff_orders/courier_orders/"
                            >Доставки</a
                        >
                    </li>
                    {% endif %}
                </ul>
            </ul>
        </nav>
        {% endcomment %}

        <main class = "main_section">{% block content %} {% endblock %}</main>
    </body>
</html>

booking/hotel_app/templates/book_room.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Book Room</title>
</head>
<body>
    <h1>Book a Room</h1>
    <form method="post">
        {% csrf_token %}
        <label for="check_in_date">Check-in Date:</label>
        <input type="date" id="check_in_date" name="check_in_date">

        <label for="check_out_date">Check-out Date:</label>
        <input type="date" id="check_out_date" name="check_out_date">

        <button type="submit">Book</button>
    </form>
</body>
</html>

booking/hotel_app/templates/home_page.html
{% extends 'base_layout.html' %} {% block title %}List of Hotels{% endblock %}
{% block content %}
<div class="features">
    <h3>List of Hotels</h3>

    {% if hotels %}
    <ul class = "hotel_list">
        {% for hotel in hotels %}
        <li>
            <h4>{{ hotel.name }}</h4>
            <p><strong>Location:</strong> {{ hotel.location }}</p>
            <p><strong>Description:</strong> {{ hotel.description }}</p>
            <p><strong>Rating:</strong> {{ hotel.rating }}</p>
            <img
                src="{{ hotel.photos.url }}"
                alt="{{ hotel.name }} Photo"
                width="200"
            />
            <p><strong>Created At:</strong> {{ hotel.created_at }}</p>
            <p><strong>Updated At:</strong> {{ hotel.updated_at }}</p>
            <a href="{% url 'hotel_detail' hotel.id %}">View Details</a>
        </li>
        {% endfor %}    
    </ul>
    {% else %}
    <p>No hotels available.</p>
    {% endif %}
</div>
{% endblock %}

booking/hotel_app/templates/hotel_detail.html
{% extends 'base_layout.html' %} {% block title %}Hotel details{% endblock %}
{% block content %}
<div class="features">
    <h1>Hotel Details</h1>
    <h2>{{ hotel.name }}</h2>
    <p><strong>Location:</strong> {{ hotel.location }}</p>
    <p><strong>Description:</strong> {{ hotel.description }}</p>
    <p><strong>Rating:</strong> {{ hotel.rating }}</p>
    <img src="{{ hotel.photos.url }}" alt="{{ hotel.name }} photo">

    <h2>Rooms</h2>
    <ul>
        {% for room in hotel.room_set.all %}
            <li>
                <h3>{{ room.room_type }}</h3>
                <p><strong>Price per Night:</strong> {{ room.price_per_night }}</p>
                <p><strong>Available:</strong> {% if room.available %} Yes {% else %} No {% endif %}</p>
                <img src="{{ room.photos.url }}" alt="{{ room.room_type }} photo">
            </li>
        {% endfor %}
    </ul>

    {% comment %} <a href="{% url 'leave_review' hotel_id=hotel.id %}">Leave a Review</a> {% endcomment %}
</div>
{% endblock %}



   

booking/hotel_app/templates/leave_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Leave Review</title>
</head>
<body>
    <h1>Leave a Review</h1>
    <form method="post">
        {% csrf_token %}
        <label for="comment">Comment:</label><br>
        <textarea id="comment" name="comment" rows="4" cols="50"></textarea><br>
        <label for="rating">Rating:</label><br>
        <input type="number" id="rating" name="rating" min="1" max="5"><br>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

booking/hotel_app/templates/room_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Room Details</title>
</head>
<body>
    <h1>Room Details</h1>
    <h2>{{ room.room_type }} at {{ room.hotel.name }}</h2>
    <img src="{{ room.photos.url }}" alt="Room Image">
    <p>Price per Night: {{ room.price_per_night }}</p>
    <p>Available: {% if room.available %} Yes {% else %} No {% endif %}</p>
</body>
</html>

booking/hotel_app/templates/user_profile.html
{% extends 'base_layout.html' %} {% block title %}List of Hotels{% endblock %}
{% block content %}
<h1>User Profile</h1>
{% comment %}
        <div>
            <h2>{{ user.username }}</h2>
            <p><strong>Email:</strong> {{ user.email }}</p>
        </div>
        {% endcomment %}
{% endblock %}

booking/hotel_app/templates/view_bookings.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Bookings</title>
</head>
<body>
    <h1>My Bookings</h1>
    <table>
        <thead>
            <tr>
                <th>Hotel</th>
                <th>Room Type</th>
                <th>Check-in Date</th>
                <th>Check-out Date</th>
            </tr>
        </thead>
        <tbody>
            {% for booking in user_bookings %}
            <tr>
                <td>{{ booking.room.hotel.name }}</td>
                <td>{{ booking.room.room_type }}</td>
                <td>{{ booking.check_in_date }}</td>
                <td>{{ booking.check_out_date }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

booking/hotel_app/templates/view_hotels.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>View Hotels</title>
</head>
<body>
    <h1>Hotels</h1>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Location</th>
                <th>Description</th>
                <th>Rating</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for hotel in hotels %}
                <tr>
                    <td>{{ hotel.name }}</td>
                    <td>{{ hotel.location }}</td>
                    <td>{{ hotel.description }}</td>
                    <td>{{ hotel.rating }}</td>
                    <td>
                        <a href="{% url 'manage_hotel_detail' hotel.id %}">View Details</a>
                        <a href="{% url 'edit_hotel' hotel.id %}">Edit</a>
                        <a href="{% url 'delete_hotel' hotel.id %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

booking/hotel_app/templates/view_rooms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Available Rooms</title>
</head>
<body>
    <h1>Available Rooms</h1>
    <div>
        <h2>Rooms at {{ hotel.name }}</h2>
        {% if rooms %}
            <ul>
                {% for room in rooms %}
                    <li>
                        <h3>{{ room.room_type }}</h3>
                        <p><strong>Price per Night:</strong> {{ room.price_per_night }}</p>
                        <p><strong>Available:</strong> {% if room.available %}Yes{% else %}No{% endif %}</p>
                        <p><strong>Amenities:</strong> {{ room.amenities }}</p>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No rooms available at the moment.</p>
        {% endif %}
    </div>
</body>
</html>